#!/usr/bin/env python3
"""Write THIRD_PARTY_LICENSES.md: every crate compiled into the release binary,
its license, and the license text (deduplicated: identical texts are printed
once with the list of crates they cover). Rerun after changing Cargo.toml."""
import json, os, re, subprocess
meta = json.loads(subprocess.check_output(["cargo", "metadata", "--format-version", "1"]))
pkgs = {(p["name"], p["version"]): p for p in meta["packages"]}
tree = subprocess.check_output(["cargo", "tree", "-e", "normal", "--prefix", "none"], text=True)
crates = sorted({tuple(l.split()[:2]) for l in tree.splitlines() if l.strip()})
crates = [(n, v.lstrip("v")) for n, v in crates if n != "rekyll"]
texts, rows = {}, []
for name, ver in crates:
    p = pkgs[(name, ver)]
    d = os.path.dirname(p["manifest_path"])
    lic = p.get("license") or "see LICENSE"
    files = sorted(f for f in os.listdir(d) if re.match(r"(LICEN[CS]E|COPYING|COPYRIGHT|NOTICE)", f, re.I))
    rows.append(f"| {name} | {ver} | {lic} | {p.get('repository') or ''} |")
    for f in files:
        body = open(os.path.join(d, f), encoding="utf-8", errors="replace").read().strip()
        key = re.sub(r"\s+", " ", body)
        texts.setdefault(key, (body, []))[1].append(f"{name} {ver} ({f})")
out = ["# Third-party licenses", "",
       "rekyll is statically linked; the binary contains code from the crates below.",
       "Dual-licensed crates (`MIT OR Apache-2.0`, `Unlicense/MIT`) are used under MIT.",
       "Generated by `scripts/licenses.py`.", "",
       "| Crate | Version | License | Source |", "|---|---|---|---|", *rows, "", "## License texts", ""]
for body, who in texts.values():
    out += ["### " + ", ".join(who), "", "```", body, "```", ""]
open("THIRD_PARTY_LICENSES.md", "w").write("\n".join(out))
print(f"{len(crates)} crates, {len(texts)} distinct license texts")
